name: "price-tracker"

on:
  push:
    branches:
      - main
  schedule: 
    - cron: "0,30 * * * *"

jobs:
  tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Configure GPG key for Git
        run: |
          git config --global user.signingkey "5C1FD06B46C9E26E"
          git config --global commit.gpgsign true

      - name: List GPG keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Pull API progress
        run: python3 src/main.py

      - name: Sign commit and push changes
        run: |
          now=$(date +"%Y-%m-%d %H:%M UTC")
          git config --global user.name "hxari"
          git config --global user.email "90847846+hxAri@users.noreply.github.com"
          git add ./public
          git commit -S -m "[BOT] Sign commit and push changes ${now}" || echo "Nothing to commit"
          git push || echo "Nothing to push"
        continue-on-error: true
