
name: "Scheduler"
on:
    push:
        branches:
            -   main
    schedule: 
        #           You can use https://crontab.guru to help generate
        #           your cron syntax and confirm what time it will run
        #           ┌───────────── minute 0, 30
        #           │    ┌───────────── hour (0 - 23)
        #           │    │ ┌───────────── day of the month (1 - 31)
        #           │    │ │ ┌───────────── month (1 - 12 or JAN-DEC)
        #           │    │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
        #           │    │ │ │ │
        -   cron:  "0,30 * * * *"
jobs:
    tracker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout v4
                uses: actions/checkout@v4
            -   name: Setup Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.11
                    cache: pip
            -   name: Installing Requirements
                run: pip install -r requirements.txt
            -   name: Pulling API progress
                run: python3 src/main
            -   name: Configure Git
                run: |
                    git config --global user.name "Action"
                    git config --global user.email "90847846+hxAri@users.noreply.github.com"
            -   name: Sign commit and push changes
                run: |
                    git add public
                    git commit -S -m "[BOT] Sign commit and push changes $(date +"%Y-%m-%d %H:%M UTC")"
                    git push
